/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
                        "on-error": "#690005",
                        "on-error-container": "#ffdad6",
                        "on-surface-variant": "#d0c5af",
                        "tertiary-fixed": "#dbe1ff",
                        "primary-fixed-dim": "#e9c349",
                        "secondary": "#e2c37d",
                        "inverse-surface": "#d6e4f7",
                        "surface-container-high": "#1e2b39",
                        "surface-container-lowest": "#020f1c",
                        "on-primary-fixed": "#241a00",
                        "on-surface": "#d6e4f7",
                        "on-tertiary-fixed": "#00174b",
                        "error-container": "#93000a",
                        "primary": "#f2ca50",
                        "on-background": "#d6e4f7",
                        "on-tertiary-fixed-variant": "#27438a",
                        "on-tertiary-container": "#254188",
                        "primary-fixed": "#ffe088",
                        "outline-variant": "#4d4635",
                        "inverse-primary": "#735c00",
                        "on-secondary-fixed-variant": "#594408",
                        "primary-container": "#d4af37",
                        "tertiary": "#bfcdff",
                        "on-secondary-container": "#cfb26d",
                        "surface-container-highest": "#293644",
                        "surface-container": "#13212e",
                        "secondary-fixed": "#ffdf97",
                        "background": "#061422",
                        "surface": "#061422",
                        "on-secondary-fixed": "#251a00",
                        "surface-dim": "#061422",
                        "on-primary": "#3c2f00",
                        "on-tertiary": "#082b72",
                        "inverse-on-surface": "#243240",
                        "error": "#ffb4ab",
                        "on-primary-fixed-variant": "#574500",
                        "surface-container-low": "#0f1d2a",
                        "secondary-fixed-dim": "#e2c37d",
                        "surface-variant": "#293644",
                        "on-secondary": "#3e2e00",
                        "tertiary-container": "#97b0ff",
                        "secondary-container": "#594408",
                        "surface-tint": "#e9c349",
                        "outline": "#99907c",
                        "tertiary-fixed-dim": "#b4c5ff",
                        "on-primary-container": "#554300",
                        "surface-bright": "#2d3a49"
                    },
                    "borderRadius": {
                        "DEFAULT": "0.125rem",
                        "lg": "0.25rem",
                        "xl": "0.5rem",
                        "full": "0.75rem"
                    },
                    "spacing": {
                        "stack-lg": "32px",
                        "stack-md": "16px",
                        "gutter": "16px",
                        "stack-sm": "8px",
                        "container-padding": "24px",
                        "unit": "4px"
                    },
                    "fontFamily": {
                        "headline-md": ["Libre Caslon Text"],
                        "label-caps": ["JetBrains Mono"],
                        "body-lg": ["Geist"],
                        "body-md": ["Geist"],
                        "display-lg": ["Libre Caslon Text"],
                        "headline-sm": ["Libre Caslon Text"],
                        "headline-md-mobile": ["Libre Caslon Text"]
                    },
                    "fontSize": {
                        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
                        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600"}],
                        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                        "headline-md-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}]
                    }
    },
  },
  plugins: [],
}